--- 
title: "MATH1710 Probability and Statistics I"
author: "[Matthew Aldridge](https://mpaldridge.github.io/)"
date: "University of Leeds, 2023--24"
site: bookdown::bookdown_site
documentclass: book
description: "Lecture notes for the course MATH1710 Probability and Statistics I at the University of Leeds, 2023--2024"
favicon: favicon.ico
url:    'https://mpaldridge.github.io/math1710/'
---

# Schedule {.unnumbered}

```{r include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

\newcommand{\Var}{\operatorname{Var}}

::: {.oldsched}
**Week 9** (27 November -- 1 December):

* [**Lecture 17:** Exponential distribution and multiple continuous random variables](#L17-exponential-multi) (Monday 27 November)
* [**Lecture 18:** Limit theorems](#L18-limit) (Wednesday 29 November)
* [**Problem Sheet 5:**](#P5) Work through in preparation for your tutorial in Week 10. Deadline for assessed questions: Monday 27 November.
* [**R Worksheet 8**](#R) -- deadline for assessed questions: Monday 4 December
* **Office hours:** Friday 1 December, 11--12 and 1--2, [Physics Research Deck 9.320](https://mpaldridge.github.io/office.html)
:::

::: {.mysched}
**Week 8** (20--24 November):

* [**Lecture 15:** Continuous random variables](#L15-continuous) (Monday 20 November)
* [**Lecture 16:** Normal distribution](#L16-normal) (Wednesday 22 November)
* **Tutorial** on [Problem Sheet 4](#P4)
* [**Problem Sheet 4:**](#P4) Work through in preparation for your tutorial. Deadline for assessed questions: Monday 27 November.
* [**R Worksheet 7**](#R)
* **Office hours:** Friday 24 November, 11--12 and 1--2, [Physics Research Deck 9.320](https://mpaldridge.github.io/office.html)
:::

::: {.mysched}
**Week 7** (13--17 November):

* [**Lecture 13:** Multiple random variables](#L13-multi-rv) (Monday 13 November)
* [**Lecture 14:** Expectation and covariance](#L14-covariance) (Wednesday 15 November)
* [**Problem Sheet 4:**](#P4) Work through in preparation for your tutorial in Week 8. Deadline for assessed questions: Monday 27 November.
* [**R Worksheet 6:**](#R) -- deadline for assessed questions: Monday 20 November
* **Office hours:** Friday 17 November, 11--12 and 1--2, [Physics Research Deck 9.320](https://mpaldridge.github.io/office.html)
:::

::: {.mysched}
**Week 6** (6--10 November):

* [**Lecture 11:** Binomial and geometric distributions](#L11-binomial-geometric) (Monday 6 November)
* [**Lecture 12:** Poisson distribution](#L12-poisson) (Wednesday 8 November)
* **Tutorial** on Problem Sheet 3
* [**Problem Sheet 3:**](#P3) Work through in preparation for your tutorial. Deadline for assessed questions: Monday 13 November.
* [**R Worksheet 5**](#R)
* **Office hours:** Friday 10 November, 11--12 and 1--2, [Physics Research Deck 9.320](https://mpaldridge.github.io/office.html)
* [Mid-semester check-in](https://forms.office.com/e/8ETiji58Zi)
:::

::: {.mysched}
**Week 5** (30 October--3 November):

* [**Lecture 9:** Discrete random variables](#L09-discrete-rv) (Monday 30 October)
* [**Lecture 10:** Expectation and variance](#L10-expectation) (Wednesday 1 November)
* [**Problem Sheet 3:**](#P3) Work through in preparation for your tutorial in Week 6. Deadline for assessed questions: Monday 13 November.
* [**R Worksheet 4**](#R) -- deadline for assessed questions: Monday 6 November
* **Office hours:** Friday 3 November, 11--1, [Physics Research Deck 9.320](https://mpaldridge.github.io/office.html) (*note change of time*)
:::

::: {.mysched}
**Week 4** (23--27 October):

* [**Lecture 7:** Independence and conditional probabilty](#L07-conditional) (Monday 23 October)
* [**Lecture 8:** Two theorems on conditional probability](#L08-two-theorems) (Wednesday 25 October)
* **Tutorial** on [Problem Sheet 2](#P2)
* [**Problem Sheet 2:**](#P2) Work through in preparation for your tutorial. Deadline for assessed questions: Monday 30 October.
* [**R Worksheet 3**](#R)
* **Office hours:** Friday 27 October, 11--12 and 1--2, [Physics Research Deck 9.320](https://mpaldridge.github.io/office.html) (*note change of venue*)
:::

::: {.mysched}
**Week 3** (16--20 October):

* [**Lecture 5:** Classical probability I](#L05-classical-i) (Monday 16 October)
* [**Lecture 6:** Classical probability II](#L06-classical-ii) (Wednesday 18 October)
* **R Practical**
* [**Problem Sheet 2:**](#P2) Work through in preparation for your tutorial in Week 4. Deadline for assessed questions: Monday 30 October.
* [**R Worksheet 2:**](#R) Deadline for assessed exercises: Monday 23 October
* **Office hours:** Friday 20 October, 11--12 and 1--2, [Maths Boardroom](boardroom.png)
:::

::: {.mysched}
**Week 2** (9--13 October):

* [**Lecture 3:** Sample spaces and events](#L03-events) (Monday 9 October)
* [**Lecture 4:** Probability](#L04-probability) (Wednesday 11 October)
* **Tutorial** on [Problem Sheet 1](#P1)
* [**R Practical**](#practical)
* [**Problem Sheet 1:**](#P1) Work through in preparation for your tutorial. Deadline for assessed questions: Monday 16 October.
* [**R Worksheet 1**](#R)
* **Office hours:** Friday 13 October, 11--12 and 1--2, [Maths Boardroom](boardroom.png)
:::

::: {.mysched}
**Week 1** (2--6 October):

* [**Lecture 1:** Summary statistics](#L01-stats) (Monday 2 October)
* [**Lecture 2:** Data visualisation](#L02-dataviz) (Wednesday 4 October)
* [**Problem Sheet 1:**](#P1) Work through in preparation for your tutorial in Week 2. Deadline for assessed questions: Monday 16 October.
* **Office hours:** Friday 6 October, 11--12 and 1--2, [Maths Boardroom](boardroom.png)
:::

<!--
::: {.oldsched}
**Week 10** (5-9 December):

* [**Lecture 19:** The Bayesian idea](#L19-bayes-idea) (Monday 5 December)
* [**Lecture 20:** More Bayesian models](#L20-bayes-models): (Wednesday 7 December)
* [**Problem Sheet 5:**](#P5) Work through the short and long questions in preparation your tutorial. Deadline for assessed questions: *Monday 12 December*
* [**R Worksheet 10:** Law of large numbers](#r-work) to be completed this week
* [**R Worksheet 11:** Recap](#r-work) next week's sheet, available now due to the unusually early deadline: Thursday 15 December
:::

::: {.mysched}
**Week 9** (28 November -- 2 December):

* [**Lecture 17:** Exponential distribution and multiple continuous random variables](#L17-exponential-multi) (Monday 28 November)
* [**Lecture 18:** Limit theorems](#L18-limit): *The lecture on Wednesday 30 November will be cancelled; instead you should learn this material from the online notes and embedded videos*
* [**Problem Sheet 5:**](#P5) Work through the short and long questions in preparation your tutorial next week. Deadline for assessed questions: *Monday 12 December*
* [**R Worksheet 9:** Normal distribution](#r-work) to be completed this week; assessed work due Monday 5 December
:::

::: {.mysched}
**Week 8** (21--25 November):

* **Tutorials:** *All in-person tutorials cancelled. Online tutorial: Wednesday 23 November at 1000; recording available on Minerva.*
* [**Lecture 15:** Continuous random variables](#L15-continuous) (Monday 21 November)
* [**Lecture 16:** Normal distribution](#L16-normal) (Wednesday 23 November)
* [**Problem Sheet 4:**](#P4) Work through the short and long questions in preparation for *the online tutorial*. Deadline for assessed questions: *Tuesday 29 November*
* [**R Worksheet 8:** Discrete random variables](#r-work) to be completed this week
:::

::: {.mysched}
**Week 7** (14--18 November):

* [**Lecture 13:** Multiple random variables](#L13-multi-rv) (Monday 14 November)
* [**Lecture 14:** Expectation and covariance](#L14-covariance) (Wednesday 16 November)
* [**Problem Sheet 4:**](#P4) Work through the short and long questions in preparation for your tutorial next week. Deadline for assessed questions: Monday 28 November.
* [**R Worksheet 7:** Discrete distributions](#r-work) to be completed this week; assessed work due Monday 21 November.
:::

::: {.mysched}
**Week 6** (7--11 November):

* [**Lecture 11:** Binomial and geometric distributions](#L11-binomial-geometric) (Monday 7 November)
* [**Lecture 12:** Poisson distribution](#L12-poisson) (Wednesday 9 November)
* **Tutorial:** to discuss Problem Sheet 3; check your timetable for details.
* [**Problem Sheet 3:**](#P3) Work through the short and long questions in preparation for your tutorial. Deadline for assessed questions: Monday 14 November.
* [**R Worksheet 6:** R Markdown](#r-work) *optional* worksheet for this week.
:::

::: {.mysched}
**Week 5** (31 October -- 4 November):

* [**Lecture 9:** Discrete random variables](#L09-discrete-rv) (Monday 31 October)
* [**Lecture 10:** Expectation and variance](#L10-expectation) (Wednesday 2 November)
* [**Problem Sheet 3:**](#P3) Work through the short and long questions in preparation for your tutorial in Week 6. Deadline for assessed questions: Monday 14 November.
* [**R Worksheet 5:** Plots II](#r-work) to be completed this week. Deadline for assessed questions: Monday 7 November.
:::

::: {.mysched}
**Week 4** (24--28 October):

* [**Lecture 7:** Independence and conditional probability](#L07-conditional) (Monday 24 October)
* [**Lecture 8:** Two theorems on conditional probability](#L08-two-theorems) (Wednesday 26 October)
* **Tutorial:** to discuss Problem Sheet 2; check your timetable for details.
* [**Problem Sheet 2:**](#P2) Work through the short and long questions in preparation for your tutorial. Deadline for assessed questions: Monday 31 October.
* [**R Worksheet 4:** Plots I](#r-work) to be completed this week.
:::

::: {.mysched}
**Week 3** (17--21 October):

* [**Lecture 5:** Classical probability I](#L05-classical-i) (Monday 17 October)
* [**Lecture 6:** Classical probability II](#L05-classical-ii) (Wednesday 19 October)
* [**Problem Sheet 2:**](#P2) Work through the short and long questions in preparation for your tutorial in Week 4. Deadline for assessed questions: Monday 31 October.
* [**R Worksheet 3:** Data in R](#r-work) to be completed this week. Deadline for assessed questions: Monday 24 October.
:::

::: {.mysched}
**Week 2** (10--14 October):

* [**Lecture 3:** Sample spaces and events](#L03-events) (Monday 10 October)
* [**Lecture 4:** Probability](#L04-probability) (Wednesday 12 October)
* **Tutorial:** to discuss Problem Sheet 1; check your timetable for details.
* [**Problem Sheet 1:**](#P1) Work through the short and long questions in preparation for your tutorial. Deadline for assessed questions: Monday 17 October.
* [**R Worksheet 2:** Vectors](#r-work) to be completed this week.
:::


::: {.mysched}
**Week 1** (3--7 October):

* [**Lecture 1:** Summary statistics](#L01-stats) (Monday 3 October)
* [**Lecture 2:** Data visualisation](#L02-dataviz) (Wednesday 5 October)
* [**Problem Sheet 1:**](#P1) Work through the short and long questions in preparation for your tutorial in Week 2. Deadline for assessed questions: Monday 17 October.
* [**R Worksheet 1:** R basics](#r-work) to be completed this week.
:::
-->
