# Exam  {#L22-exam}

## About the exam

First, the details of the exam:

* Check your exam timetable for the date and time of the exam. For most people (without unusual clashes or special arrangements), the exam will happen on **Tuesday 11 January at 0900**.
* The exam will happen in person on campus.
* The exam will last for 2 hours (except for some students with special arrangements).
* You are allowed to use a basic non-programmable calculator for the exam.
* The exam will be "closed-book" style: you are not permitted to bring notes into the exam hall.
* The exam will contain multiple-choice questions, short questions, and long questions. See below for more details about the structure of the exam.
* A page of [statistical tables for the normal distribution](https://mpaldridge.github.io/math1710/stat-tab.pdf) will be attached to the exam paper. There will not be a formula book.
* The exam makes up 70% of your mark for this module. The pass mark for this module is 40%. You must pass the exam to pass the module. The pass mark for the exam is also 40%, or 32 marks out of 80.

The exam will be in three sections:

* **Section A** contains 10 multiple-choice questions, worth 2 marks each, for a total of 20 marks. These each require a single letter answer. You will enter these letter answers on a multiple-choice "bubble sheet"; there is an example of this sheet on Minerva.
* **Section B** contains 10 single-part "short answer" questions, worth 2 marks each, for a total of 20 marks. This require a clear answer and brief working or explanation. You will answer these in an answer booklet.
* **Section C** contains 2 multi-part "long answer" questions, worth 20 marks each, for a total of 40 marks. Parts of these questions require full detailed answers, as in assessed work from problem sheets. You will answer these in the same answer booklet.

## Past papers

Three **past papers** for MATH1710 are available: the 2018--19, 2019--20, and 2020--21 papers. I strongly recommend using all these past papers as part of your revision. University policy is only to provide "checksheets", rather than full answers -- these allow you to check that your numerical answers are correct, but do not give full details.

Some notes on the past papers:

* General comments
  * Most past papers write $\Pr(A)$ for probabilities, where we write $\mathbb P(A)$. Most past papers write $\mathrm{E}[X]$ for expectations, where we write $\mathbb EX$.
  * Some past papers write $\subseteq$ for "is a subset of", where we write $\subset$.
  * In R questions, often `=` is used for assignment, as in `variable = 2 + 3`, whereas we prefer to use `<-`, as in `variable <- 2 + 3`.
  * Although the 2018--19 and 2019--20 papers in Section A instructed students to "write down a single letter", you will fill in your multiple-choice answers on the "bubble sheet" provided.
* 2018--19 paper:
  * Questions A6 and B9: This writes $\Omega_X$ for the range (or "range space") of a random variable $X$, where we wrote $\operatorname{Range}(X)$.
  * Question C2(b): Some of the notation here is a bit different to ours; for example, writing $l(x|p)$ for the likelihood.
* 2019--20 paper:
  * Question B9: You are not expected to be able to answer this question.
  * Question C2(b): Some of the notation here is a bit different to ours; for example, writing $l(x|p)$ for the likelihood.
* 2020--21 paper:
  * Because this was a "take-home" paper, there was no multiple-choice section, which it was thought would be too easy for nefarious students to cheat on. Instead, there were twice as many short questions.
  * Because this was an "open-book" paper, there were fewer "fact" questions than usual, such as stating definitions or giving standard proofs from the notes.
  * Question A11(ii): You are not expected to be able to answer this question.
  * Question A12: An event $A$ is said to be "preferable" for an event $B$ is $\mathbb P(B \mid A) > \mathbb P(A)$. You are not expected to know this definition (although, once told the definition, you should be able to work with it).
  * Question A18: You are not expected to be able to answer this question.

<!--
## Revision

It seems a bit strange for me to be giving you revision advice -- I last did a maths exam more than a decade ago, while you last did a maths exam a few months ago!
-->