# (PART\*) Other stuff  {-}

# The last section {#S11-summary}

## Summary of the module

We've now reached the end of the mathematical portion of MATH1710 Probability and Statistics I. This last section will be about summarising what we've learned, and starting to prepare for the exam.

Here is a summary of what we have learned in the course. You may like to use this list to guide your revision.

* **Exploratory data analysis**: Summary statistics, data visualisation, binned data
* **Probability**:
   * Probability with events: Probability spaces, probability axioms, properties of probability including the addition rule for unions, "classical probability" of equally likely events, ways of counting for classical probability, independence, conditional probability, law of total probability, Bayes' theorem
   * Probability with random variables: Discrete random variables, expectation and variance, binomial distribution, geometric distribution, Poisson distribution, multiple random variables: joint, marginal and conditional distributions, law of large numbers, continuous random variables, exponential distribution, normal distribution, central limit theorem
* **Bayesian statistics**: Bayesian framework, Beta prior, Beta--Bernoulli model, normal--normal model

We spent 1 week on EDA, 8 weeks on probability, and 1 week on Bayesian statistics. You can expect a similar proportion of your exam on each topic.

The following two tables summarise the discrete and continuous distributions we learned about in the course. In general, you are expected to know this material in the exam without being told; so I *strongly recommend* learning this.

| Distribution | Range | PMF | Expectation | Variance |
|:----|:-:|:-:|:-:|:-:|
| **Bernoulli:** $\text{Bern}(p)$ | $\{0,1\}$ | $p(0) = 1- p$, $p(1) = p$ | $p$ | $p(1-p)$ |
| **Binomial:** $\text{Bin}(n,p)$ | $\{0,1,\dots,n\}$ | $\displaystyle\binom{n}{x} p^x (1-p)^{n-x}$ | $np$ | $np(1-p)$ |
| **Geometric:** $\text{Geom}(p)$ | $\{1,2,\dots\}$ | $(1-p)^{x-1}p$ | $\displaystyle\frac{1}{p}$ | $\displaystyle\frac{1-p}{p^2}$ |
| **Poisson:** $\text{Po}(\lambda)$ | $\{0,1,\dots\}$ | $\mathrm{e}^{-\lambda} \displaystyle\frac{\lambda^x}{x!}$ | $\lambda$ | $\lambda$ |

| Distribution | Range | PDF | Expectation | Variance |
|:-----|:-:|:-:|:-:|:-:|
| **Exponential:** $\text{Exp}(\lambda)$ | $\mathbb R_+$ | $\lambda \mathrm e^{-\lambda x}$ | $\displaystyle\frac{1}{\lambda}$ | $\displaystyle\frac{1}{\lambda^2}$ |
| **Normal:** $\mathrm N(\mu,\sigma^2)$ | $\mathbb R$ | ${\displaystyle{\small \frac{1}{\sqrt{2\pi\sigma^2}} \exp \left( - \frac{(x - \mu)^2}{2\sigma^2} \right)}}$ | $\mu$ | $\sigma^2$ |
| **Beta:** $\text{Beta}(\alpha, \beta)$ | $[0,1]$ | $\propto x^{\alpha - 1}(1-x)^{\beta - 1}$ | $\displaystyle\frac{\alpha}{\alpha + \beta}$ | ${\displaystyle{\small \frac{\alpha\beta}{(\alpha + \beta)^2(\alpha + \beta + 1)}}}$ |



## About the exam

First, the details of the exam:

* Check your exam timetable for the date and time of the exam. For most people (without unusual clashes or special arrangements), the exam will happen on **Tuesday 11 January at 0900**.
* The exam will happen in person on campus.
* The exam will last for 2 hours (except for some students with special arrangements).
* You are allowed to use a basic non-programmable calculator for the exam.
* The exam will be "closed-book" style: you are not permitted to bring notes into the exam hall.
* The exam will contain multiple-choice questions, short questions, and long questions. See below for more details about the structure of the exam.
* A page of [statistical tables for the normal distribution](https://mpaldridge.github.io/math1710/stat-tab.pdf) will be attached to the exam paper. There will not be a formula book.
* The exam makes up 70% of your mark for this module. The pass mark for this module is 40%. You must pass the exam to pass the module. The pass mark for the exam is also 40%, or 32 marks out of 80.

The exam will be in three sections:

* **Section A** contains 10 multiple-choice questions, worth 2 marks each, for a total of 20 marks. These each require a single letter answer. You will enter these letter answers on a multiple-choice "bubble sheet"; there is an example of this sheet on Minerva.
* **Section B** contains 10 single-part "short answer" questions, worth 2 marks each, for a total of 20 marks. This require a clear answer and brief working or explanation. You will answer these in an answer booklet.
* **Section C** contains 2 multi-part "long answer" questions, worth 20 marks each, for a total of 40 marks. Parts of these questions require full detailed answers, as in assessed work from problem sheets. You will answer these in the same answer booklet.

## Past papers

Three **past papers** for MATH1710 are available: the 2018--19, 2019--20, and 2020--21 papers. I strongly recommend using all these past papers as part of your revision. University policy is only to provide "checksheets", rather than full answers -- these allow you to check that your numerical answers are correct, but do not give full details.

Some notes on the past papers:

* General comments
  * Most past papers write $\Pr(A)$ for probabilities, where we write $\mathbb P(A)$. Most past papers write $\mathrm{E}[X]$ for expectations, where we write $\mathbb EX$.
  * Some past papers write $\subseteq$ for "is a subset of", where we write $\subset$.
  * In R questions, often `=` is used for assignment, as in `variable = 2 + 3`, whereas we prefer to use `<-`, as in `variable <- 2 + 3`.
  * Although the 2018--19 and 2019--20 papers in Section A instructed students to "write down a single letter", you will fill in your multiple-choice answers on the "bubble sheet" provided.
* 2018--19 paper:
  * Questions A6 and B9: This writes $\Omega_X$ for the range (or "range space") of a random variable $X$, where we wrote $\operatorname{Range}(X)$.
  * Question C2(b): Some of the notation here is a bit different to ours; for example, writing $l(x|p)$ for the likelihood.
* 2019--20 paper:
  * Question B9: You are not expected to be able to answer this question.
  * Question C2(b): Some of the notation here is a bit different to ours; for example, writing $l(x|p)$ for the likelihood.
* 2020--21 paper:
  * Because this was a "take-home" paper, there was no multiple-choice section, which it was thought would be too easy for nefarious students to cheat on. Instead, there were twice as many short questions.
  * Because this was an "open-book" paper, there were fewer "fact" questions than usual, such as stating definitions or giving standard proofs from the notes.
  * Question A11(ii): You are not expected to be able to answer this question.
  * Question A12: An event $A$ is said to be "preferable" for an event $B$ is $\mathbb P(B \mid A) > \mathbb P(A)$. You are not expected to know this definition (although, once told the definition, you should be able to work with it).
  * Question A18: You are not expected to be able to answer this question.

<!--
## Revision

It seems a bit strange for me to be giving you revision advice -- I last did a maths exam more than a decade ago, while you last did a maths exam a few months ago!
-->