# Problem Sheet 1  {#P1 .unnumbered}

::: {.mysummary}
This is Problem Sheet 1, which covers material from [Section 1](#S01-eda) of the notes. You should work through all the questions on this problem sheet during week 1, in preparation for your tutorial in week 2. Questions C1 and C2 are assessed questions, and are due in by **2pm on Friday 8 September**. I recommend spending about 3 hours on this problem sheet in week 1, plus 1 extra hour in week 2 to neatly write up and submit your answers to the assessed questions.
:::

## A: Short questions {#P1-short .unnumbered}

::: {.mysummary}
The first XXX questions are **short questions**, which are intended to be mostly not too difficult. Short questions usually follow directly from the material in the notes. Here, your should clearly state your final answer, and give enough working-out (or a short written explanation) for it to be clear how you reached that answer. You can check your answers with the solutions-without-working at the bottom of this sheet; solutions-with-working will be available later. If you get stuck on any of these questions, you might want to ask for guidance in your tutorial.
:::


## B: Long questions {#P1-long .unnumbered}

::: {.mysummary}
The next four questions are **long questions**, which are intended to be harder. Long questions often require you to think for yourself, not just copy ideas from the notes. Here, your answers should be written in complete sentences, and you should carefully explain in words each step of your working. Your answers to these questions -- not only their mathematical content, but also how to clearly write good solutions -- are likely to be the main topic for discussion in your tutorial.
:::

```{r, child = "problems/questions/P1-long.Rmd"}
```

## C: Assessed questions {#P1-assessed .unnumbered}

::: {.mysummary}
The last two questions are **assessed questions**. This means you will submit your answers, and your answers will be marked. These two questions count for 3% of your mark for this module.

The deadline for submitting your solutions is **2pm on Friday 8 September**. Submission will be via Gradescope; submission will open on Monday 3 September. You should submit your answers as a single PDF file. Most students choose to hand-write their work, then scan it to PDF using their phone; if you do this, you should use a proper scanning app (like Microsoft Lens or Adobe Scan) -- please do not just submit photographs. We will discuss Gradescope submission further in the week 2 lectures. Your work will be marked by your tutor and returned on Monday 18 September, when solutions will also be made available.

Question C1 is a "short question", where showing brief working is sufficient; Question C2 is a "long question" that requires full sentences and very clear explanations. If you get stuck, your tutor may be willing to give you a little hint in tutorial.
:::

## Solutions to short questions {#P1-short-sols .unnumbered}