::::: {.myq}
**A1.** Consider again the "number of Skittles in each packet" data from Example 1.1.
\[ 59, \ 59, \ 59, \ 59, \ 60, \ 60, \ 60, \ 61, \ 62, \ 62, \ 62, \ 63, \ 63 .\]

:::: {.subq}
**(a)** Calculate the mean number of Skittles in each packet.

::: {.myanswers data-latex=""}
*Solution.* This was in the notes:
\[ \bar x = \frac{1}{13} (59 + 59 + \cdots + 63) =  \frac{789}{13} = 60.7 .\]
:::
::::

:::: {.subq}
**(b)** Calculate the sample variance using the computational formula.

::: {.myanswers data-latex=""}
*Solution.*
\begin{align*}
s_x^2 &= \frac{1}{13 - 1} \left( (59^2 + 59^2 + \cdots + 63^2) - 13 \times 60.6923^2)\right) \\
      &= \frac{1}{12} (47915 - 47886.2) \\
      &= 2.40
\end{align*}

**Group feedback:** With the computational formula, the value $\sum_i x_i^2 - n \bar{x}^2$ is typically a fairly small number given as the difference between two very big numbers $\sum_i x_i^2$ and $n \bar x^2$. This means you have to get the two big numbers very precise, to ensure the cancellation happens correctly; in particular, make sure you use plenty of decimal places of accuracy in $\bar x$.
:::
::::

:::: {.subq}
**(c)** Calculate the sample variance using the definitional
formula.

::: {.myanswers data-latex=""}
*Solution.*
\begin{align*}
s_x^2 &= \frac{1}{13 - 1} \left( (59 - 60.7)^2 + (59 - 60.7)^2 + \cdots + (63 - 60.7)^2 \right) \\
      &= \frac{1}{12} (2.86 + 2.86 + \cdots + 5.33) \\
      &= \frac{1}{12} \times 28.77 \\
      &= 2.40
\end{align*}
:::
::::

:::: {.subq}
**(d)** Out of (b) and (c), which calculation did you find easier, and why?

::: {.myanswers data-latex=""}
*Solution.* The computational formula required fewer presses of the calculator buttons, because $\sum_i x_i^2$ is fewer button-presses than $\sum_i (x_i - \bar x)^2$, where you have to subtract the means before squaring.

On the other hand, the expression inside the brackets of the computational formula is a fairly small number given as the difference of two very large numbers, so it was necessary to use lots of decimal places of accuracy in $\bar x$ to make sure the second large number was accurate and therefore that the subtraction cancelled correctly.

**Group feedback:** Many answer for (d) are fine provided you give a justification.
:::
::::
:::::

::::: {.myq}
**A2.** Consider the following data sets of the age of elected politicians on a local council. (The "18--30" bin, for example, means from one's
18th birthday to the moment before one's 30th birthday, so lasts 12 years.)

|   Age (years)    | Frequency | Relative frequency | Frequency density |
|:---------------:|:---------:|:------------------:|:-----------------:|
|   18--30   |     1     |            |              |
|   30--40   |     3     |            |              |
|   40--45   |     4     |            |              |
|   45--50   |     5     |            |              |
|   50--55   |     3     |            |              |
|   55--60   |     1     |            |              |
|   60--70   |     3     |            |              |
|    **Total**    |    20    |          1         |      ---             |

:::: {.subq}
**(a)** Complete the table by filling in the relative frequency and
frequency densities.

::: {.myanswers data-latex=""}
*Solution.*

|   Age (years)    | Frequency | Relative frequency | Frequency density |
|:---------------:|:---------:|:------------------:|:-----------------:|
| 18--30   |     1     |    0.05    |     0.0041        |
|   30--40   |     3  |  0.15     |       0.015      |
|   40--45   |     4    |   0.2     |  0.04     |
|   45--50   |     5    |   0.25      |    0.05      |
|   50--55   |  3    |   0.15     |        0.03      |
|   55--60   |     1     |    0.05    |  0.01        |
|   60--70   |     3     |    0.15    |       0.015       |
|  **Total**    |    20    |          1         |      ---             |

:::
::::

:::: {.subq}
**(b)** What is the median age bin?

::: {.myanswers data-latex=""}
*Solution.* The 10th- and 11th-largest observations are both in the 45--50 bin, which is therefore the median bin.
:::
::::

:::: {.subq}
**(c)** What is the modal age bin?

::: {.myanswers data-latex=""}
*Solution.* The bin with the largest frequency density is 45--50, which is therefore the modal bin.
:::
::::

:::: {.subq}
**(d)** Calculate (the standard approximation of) the mean age of the politicians.

::: {.myanswers data-latex=""}
*Solution.* Pretending that each person is in the centre of their bin, we have
\[ \bar x = \frac{1}{20} (1\times24 + 3\times 35 + \cdots + 3 \times 65) = \frac{946.5}{20} = 47.3 . \]
:::
::::
:::::

:::: {.myq}
**A3.** Consider the two datasets illustrated by the boxplots below. Write down some differences between the two datasets.

```{r, echo = FALSE, fig.width=5}
set.seed(6)
x <- rnorm(80, 10, 2)
y <- 8 + rexp(80,0.4)
boxplot(x, y, names = c("Dataset 1", "Dataset 2"))
```

::: {.myanswers data-latex=""}
*Solution.* Some answers could be:

* The median and inter-quartile range of Dataset 2 appear to be very slightly larger than those in Dataset 1, although the differences are very small and might not be important in real life.
* Dataset 2 has a few outliers; Dataset 1 has none.
* While Dataset 1 is fairly "balanced" either side of the median, Dataset 2 shows what statisticians call a "positive skew": the data above the median is much more spread out than the data below the median.

**Group feedback:**
You can probably think of other answers.
:::
::::