# R Practical 1 {#practical .unnumbered}

::: {.mysummary}
[**R Worksheet 1** is here](R1.html)
:::


## About the Practical  {#about-prac .unnumbered}

The first computer practical sessions are this week to introduce you to the R programming language. You should make sure:

* You know [where](#directions) and when your practical session is -- check your timetable!
* You know your username, password, and the Duo authentication system to log on to university computers.
* To bring your laptop along if (optionally) you want to install R and RStudio on it.

[Below are some directions](#directions) of how to find the various computer clusters.


## What are R and RStudio?  {#what-is-r .unnumbered}

* **R** is a *programming language* that is particularly useful for working with probability and statistics. The R language is very widely used in universities and increasingly widely used in industry. Learning to use R is a mandatory part of this module, and exercises requiring use of R make up at least 15% of your module mark. Many other statistics-related modules at the University also use R.
* **RStudio** is a *computer program* (or *app*) that gives a convenient way to work with the language R. The RStudio program is made by the company Posit. THe program RStudio is the most common way to use the language R, and learning to use RStudio is strongly recommended.

R and RStudio are free/open-source software.

There are a number ways you can use R and RStudio:

1. *On University computers.* You will learn how to use R and RStudio on University computers in your first practical session, in Week 2.
2. *On your own computer.* R and RStudio can easily be installed on Windows and Mac laptops. Bring your laptop along to the first practical session to learn how to install R and RStudio.
3. *Using the [Posit Cloud](https://posit.cloud).* The [Posit Cloud](https://posit.cloud) is a way to use R and RStudio online -- sort of like a "Google Docs for R". You can use it free for 25 hours a month, which should be plenty for this module, or pay for more. I recommend the Posit Cloud for using R/RStudio with Chromebooks, tablet computers, or when borrowing someone else's device.

## Accessing R and RStudio on University computers  {#r-uni .unnumbered}

R and RStudio can be used on University computers via the AppsAnywhere portal. AppsAnywhere is the University of Leeds system for loading "unusual" programs (common programs like Microsoft Office and web browsers are preloaded).

There are three steps to using R and RStudio on University computers:

1. Open the AppsAnywhere portal.
2. Load the language R onto your computer.
3. Open the program RStudio.

First, open the AppsAnywhere portal by double-clicking on the desktop icon. This will open a web browser, and invite you to "Open AppsAnywhere Launcher" -- you should accept and open. AppsAnywhere has loaded properly when the blue "Validation in progress..." box turns into a green "Validation Successful" box.

Second, launch R from AppsAnywhere. R is called "Cran R 4.2.0 x64" on AppsAnywhere, so searching for "Cran" is an easy way to find it. Click "Launch".

This will do two things. First, it will silently load the language R in the background. Second, it will open a program called "RGui". RGui is basically like an older and less good version of RStudio; we do not recommend using the RGui program, so you can close it. (The R language will remain loaded.)

Third, launch RStudio from AppsAnywhere. The most recent version on AppsAnywhere is "RStudio 2023 (03.0.386)". Click "Launch". After a few second, RStudio will launch. (If invited to choose a version of the language R, pick "64-bit". If invited to update R or RStudio, decline.)

You need to repeat all three steps each time you log onto a University computer.


## Installing R and RStudio  {#r-install .unnumbered}

When you install R and RStudio, it's important that you install the language R first, and only install the program RStudio after the language R has already been installed. This ensures that RStudio can "find" R on your computer.

1. *First*, install R. Go to the [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/) and follow the instructions:

   * Windows: Click ["Download R for Windows"](https://cran.r-project.org/bin/windows/), then ["Install R for the first time"](https://cran.r-project.org/bin/windows/base/). The main link at the top should be to download the most recent version of R.
   * Mac: Click [Download R for macOS](https://cran.r-project.org/bin/macosx/), and then download the relevant PKG file. (Most modern Macbooks are based on Apple's M1 or M2 processors, so you can choose "Apple silicon arm64 build". Some older Macbooks, mostly 2020 or earlier, have Intel processors; for these you should use the "Intel 64-bit build".)
   
2. *After* R is installed, *then* install RStudio. Go to the ["Download RStudio" page at posit.co](https://posit.co/download/rstudio-desktop/) and follow the instructions. You want "RStudio Desktop" and you want the free version, if given a choice.

Now, whenever you want to use R and RStudio, simply open program RStudio. (The language R will automatically be loaded on your computer.)

For Chromebooks, we recommend using the [Posit Cloud](https://posit.cloud), as mentioned above. However, if you have an Intel-based Chromebook and are feeling brave, then we have had success installing R and RStudio using [these instructions](https://levente.littvay.hu/chromebook/), which are long and complicated.


## Where are the computer clusters?  {#directions .unnumbered}

### EC Stoner Cluster 6.68  {#stoner .unnumbered}

[**EC Stoner Cluster 6.68** [map]](ecstoner.png) is in the **EC Stoner building**. The easiest way to enter the 6th floor of EC Stoner is via the sliding doors ("South Entrance 4") opposite the multi-storey car park ([red arrow](ecstoner.png)).

Alternatively, from the "red route" along the 10th floor corridor of EC Stoner, go all the way along to the School of Food Science and Nutrition, by staircase 4, and take the lift (*not* the stairs) to the 6th floor ([blue dotted line](ecstoner.png)).

EC Stoner Cluster 6.68 is the big room to the east (right from the doors; left from the lift), through the smaller ante-room.

### Fourman O & P Clusters  {#fourman .unnumbered}

The [**Fourman O & P Clusters** [map]](fourman.png) are in the **Worsley building**, at the south of campus. The easiest route is from Chancellor's Court, next to the Roger Stevens building: follow the North--South Access Route alongside and then through the Garstang building, and enter the Worsley building at the 7th floor "airport lounge" area ([red arrow](fourman.png)). Follow the signs to "Central Teaching Space": turn left to get to the East staircase, and go up one floor the the 8th floor.

Alternatively, enter the Worsley building on Clarendon Way at the 4th floor ([blue arrow](fourman.png)). The East lifts are to your left: take the lift to the 8th floor.

On the 8th floor of the Worsley building, the Fourman Clusters are two connected rooms right next the East staircase/lifts – Fourman O is on the right; Fourman P is on the left.

### Irene Manton North & South Clusters  {#manton .unnumbered}

The [**Irene Manton Clusters** [map]](manton.png) are in the **Irene Manton building**, which is behind the Roger Stevens building. You can get there out the back door of Roger Stevens, by LT 01, or via the gardens to the right of Roger Stevens.

Walking down the walkway alongside the Irene Manton building, there's a modest, unassuming door on your left. Enter it. Irene Manton North is the room to your left; Irene Manton South is to your right.

### Psychology Cluster 1.43  {#psychology .unnumbered}

[**Psychology Cluster 1.43** [map]](psychology.png) is in the **Psychology building**, which is in between the two main east–west thoroughfares through campus -- University Road and Beach Grove Terrace/Precinct/Lifton Place. One entrance to Psychology is on Lifton Place, opposite Cromer Street, up some steps; the other is on University Road, opposite the School of Fine Art, through a little garden.

Once inside Psychology, there are signs to the "CBL clusters". Follow a long winding corridor to the east (right from Lifton Place entrance; left from University Road entrance), past a giant glittery brain sculpture, all the way to a spiral staircase. Go up one floor. Psychology Cluster 1.43 is the room on the right.

### Richard Hughes Cluster  {#hughes .unnumbered}

The [**Richard Hughes Cluster** [map]](richard-hughes.png) is on the side of the **Clothworkers' Link building**, on the north side of University Road by the "Clothworkers' Link" -- the sky-bridge that goes over University Road.

Just to the west (Hyde Park side) of the Link bridge, go up the alleyway between the Clothworkers' Link building and 28 University Road. Enter a small door on the right; the Richard Hughes Cluster is at the top of a short flight of stairs to your left.
