# R Worksheets {#R .unnumbered}

## R worksheets  {#r-work .unnumbered}

Each week there will be an R worksheet to work through in your own time. I recommend spending about one hour on each worksheet, plus one extra hour for worksheets with assessed questions, for checking and submitting your solutions.

| Week | Worksheet                     | Deadline for assessed work |
|:----:|-------------------------------|:--------------------------:|
|   1  |  [**R basics**](https://mpaldridge.github.io/math1710/R1.html) ([Solutions](https://mpaldridge.github.io/math1710/R1-solutions.html)) | --- |
|   2  |  [**Vectors**](https://mpaldridge.github.io/math1710/R2.html)   | --- |
|   3  |  [**Data in R**](https://mpaldridge.github.io/math1710/R3.html)  | Monday 24 October (Week 4) |
|   4  |  [**Plots I:** Making plots](https://mpaldridge.github.io/math1710/R4.html)   | --- |
|   5  |  [**Plots II:** Making plots better](https://mpaldridge.github.io/math1710/R5.html)  | Monday 7 November (Week 6) |
|   6  |  [**RMarkdown** (optional)](https://mpaldridge.github.io/math1710/R6.html) [[Rmd](https://mpaldridge.github.io/math1710/R6.Rmd)] | --- |
|   7  |  [**Discrete distributions**](https://mpaldridge.github.io/math1710/R7.html) [[Rmd](https://mpaldridge.github.io/math1710/R7.Rmd)]    |      Monday 21 November (Week 8)   |
|   8  |  [**Discrete random variables**](https://mpaldridge.github.io/math1710/R8.html) [[Rmd](https://mpaldridge.github.io/math1710/R8.Rmd)] | --- |
|   9  |  [**Normal distribution**](https://mpaldridge.github.io/math1710/R9.html) [[Rmd](https://mpaldridge.github.io/math1710/R9.Rmd)] | Monday 5 December (Week 10) |
|  10  |  [**Law of large numbers**](https://mpaldridge.github.io/math1710/R10.html) [[Rmd](https://mpaldridge.github.io/math1710/R10.Rmd)] |             ---           |
|  11  |  [**Recap**](https://mpaldridge.github.io/math1710/R11.html) | Thursday 15 December (Week 11) |

<!--
|   2  |  [**Vectors**](https://mpaldridge.github.io/math1710/R2.html)   | --- |
|   3  |  [**Data in R**](https://mpaldridge.github.io/math1710/R3.html) | Monday 18 October |
|   4  |  [**Plots I:** Making plots](https://mpaldridge.github.io/math1710/R4.html) | --- |
|   5  |  [**Plots II:** Making plots better](https://mpaldridge.github.io/math1710/R5.html) | Monday 1 November |
|   6  |  [**RMarkdown** (optional)](https://mpaldridge.github.io/math1710/R6.html) [[Rmd](https://mpaldridge.github.io/math1710/R6.Rmd)] | --- |
|   7  |  [**Discrete distributions**](https://mpaldridge.github.io/math1710/R7.html) [[Rmd](https://mpaldridge.github.io/math1710/R7.Rmd)]      |      Monday 15 November    |
|   8  |  [**Discrete random variables**](https://mpaldridge.github.io/math1710/R8.html) [[Rmd](https://mpaldridge.github.io/math1710/R8.Rmd)] | --- |
|   9  |  [**Normal distribution**](https://mpaldridge.github.io/math1710/R9.html) | Monday 29 November |
|  10  |  ~~Law of large numbers~~     |             ---           |
|  11  |   [**Recap**](https://mpaldridge.github.io/math1710/R11.html) | Thursday 16 December |
-->

## About R and RStudio  {#about-r .unnumbered}

* **R** is a *programming language* that is particularly useful for working with probability and statistics. R is very widely used in universities and increasingly widely used in industry. Learning to use R is a mandatory part of this module, and exercises requiring use of R make up at least 15% of your module mark. Many other statistics-related modules at the University also use R.
* **RStudio** is a *program* that gives a convenient way to work with the language R. RStudio is the most common way to use the language R, and learning to use RStudio is strongly recommended.

R and RStudio are free/open-source software.


## How to access R and RStudio  {#r-access .unnumbered}

There are a few ways you can access R and RStudio.

First, you can **install R and RStudio on your own computer**. Students who have their own computer (with administration and installation rights) usually find this the most convenient way use R.

When you install R and RStudio, it's important that you install R (the programming language) first, and only install RStudio (the program to use R) after R has already been installed. This ensures that RStudio can "find" R on your computer.

1. *First*, install R. Go to the [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/) and follow the instructions:

   * Windows: Click ["Download R for Windows"](https://cran.r-project.org/bin/windows/), then ["Install R for the first time"](https://cran.r-project.org/bin/windows/base/). The main link at the top should be to download the most recent version of R.
   * Mac: Click [Download R for macOS](https://cran.r-project.org/bin/macosx/), and then download the relevant PKG file. (For typically older Intel-based Macbooks, you must use the "Intel 64-bit build"; for post-November 2020 M1 or M2-based "Apple silicon" Macbooks, the "Apple silicon arm64 build" may be slightly faster.)
2. *After* R is installed, *then* install RStudio. Go to [the Download page at RStudio.com](https://www.rstudio.com/products/rstudio/download/#download) and follow the instructions. You want "RStudio Desktop", and you want the free version.

If you have difficulty installing R, come along to the R troubleshooting drop-in session in Week 2 and bring your computer with you (if it's sufficiently portable), and we'll do our best to help.

Second, you can **use R and RStudio on University computers**. All University computers have access to R and RStudio, via the AppsAnywhere service. *First*, launch R via AppsAnywhere (at the time of writing, it's confusingly named "Cran R 4.2.0 x64"). You can then close the program that opens. *Then* launch RStudio ("Rstudio 2022"), also via AppsAnywhere. (You can decline any updates that are suggested.)

The R drop-in sessions take place in computer rooms, so if you have problems accessing R and RStudio on University computers, you can get help at the drop-in sessions too.

Third, you can **use the [RStudio Cloud](https://rstudio.cloud/)**. The RStudio Cloud is a cloud-hosted "Google Docs for R" that you can use through your web browser, without having to install anything. You can get 25 hours per month for free, which should be plenty for this module, or pay for more.

If you have access to a computer on which you can't install software, such as some Chromebooks or tablet computers, or if you're borrowing a friend's laptop, the RStudio Cloud can be a convenient solution. 

*Update:* If you have an Intel-based Chromebook, then we have had success installing R and RStudio using [these (rather complicated) instructions](https://levente.littvay.hu/chromebook/), although you may still find it more convenient just to use the RStudio Cloud.



## R troubleshooting drop-in sessions  {#troubleshooting .unnumbered}

You will learn to use R by working through the R Worksheets. Learning to use a programming language is different from learning mathematics: you should expect to regularly get frustrated and annoyed when the computer seems to refuse to do what you want it to (but also occasionally experience the joy of getting it right!). This is a normal part of learning.

However, many students find getting with started with R in the first few weeks particularly difficult. Also, sometimes students have problems installing R and RStudio on their own computers. To help with this, we have organised optional R troubleshooting drop-in sessions in Weeks 2 and 3. Check your timetable for details -- they are probably listed as "computer practicals".



